apiVersion: v1
kind: Pod
metadata:
  name: master-tdbwv
  labels:
    name: master-tdbwv
spec:
  volumes:
    - name: data
      hostPath:
        path: /data/mysql_data
  containers:
    - name: master-tdbwv
      image: mysql-master:v1.0
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: uggTKd3xsIMM
        - name: MYSQL_REPLICATION_USER
          value: repl
        - name: MYSQL_REPLICATION_PASSWORD
          value: RQfUjBff
      ports:
        - containerPort: 3306
          name: master-tdbwv
      volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
      resources:
          limits:
            cpu: 2
            memory: 200Mi
  nodeName: localhost
---
apiVersion: v1
kind: Service
metadata:
  name: master-tdbwv
  labels:
    name: master-tdbwv
spec:
  type: NodePort
  ports:
    - port: 3306      
      nodePort: 
  selector:
    name: master-tdbwv
